name = "snaplink"
compatibility_date = "2026-07-20"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_NAMESPACE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "snaplink-images"
preview_bucket_name = "snaplink-images"
